articles/urls.py
from django.urls import path
from .views import ListIndex, ArticleDetail, add_comment_to_article

urlpatterns = [
    path('', ListIndex.as_view(), name='article-list'),
    path('<int:pk>/', ArticleDetail.as_view(), name='article-detail'),
    path('<int:pk>/comment/', add_comment_to_article, name='add_comment_to_article'),
]

firstwebsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')), # it was authorization by django built-in features
    path('articles/', include('articles.urls')),
    path('rubric/', include('rubric.urls')),
    path('accounts/', include('accounts.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import MainViews

urlpatterns = [
    path('', MainViews.as_view(), name='main')
]

articles/models.py
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from django.db import models
# from django.utils import timezone


class Rubric(models.Model):

    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.SET_NULL,
                               null=True)
    rubric_name = models.CharField(_('Rubric name'), max_length=255)
    insert_date = models.DateTimeField(_('Insert Date'), auto_now_add=True)
    update_date = models.DateTimeField(_('Update Date'), auto_now=True)

    def __str__(self):
        return self.rubric_name


class ArticleManager(models.Manager):
    def published(self):
        return self.get_queryset().filter(status=Article.PUBLISHED)

    def drafted(self):
        return self.get_queryset().filter(status=Article.DRAFT)

    def archived(self):
        return self.get_queryset().filter(status=Article.ARCHIVED)


def generate_filename(instance, filename):  # for generate comprehensible file name
    filename = instance.title + '.jpg'
    return '{0}/{1}'.format(instance, filename)


class Article(models.Model):
    DRAFT = 1
    PUBLISHED = 2
    ARCHIVED = 3

    objects = ArticleManager()

    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.SET_NULL,
                               null=True)
    rubric = models.ForeignKey('articles.Rubric', related_name='articles',
                               on_delete=models.SET_NULL,
                               null=True, blank=True)
    title = models.CharField(_('Article Title'), max_length=255)
    slug = models.CharField(_('Slug'), max_length=255, help_text=_(
        'For SEO'
    ))

    content = models.TextField(null=True, blank=True)

    image = models.ImageField(upload_to=generate_filename, null=True, blank=True)

    created_at = models.DateTimeField(_('Created At'), auto_now_add=True)

    status = models.PositiveSmallIntegerField(_('Status'),
                                              db_index=True,
                                              choices=(
                                                  (DRAFT, _('Draft')),
                                                  (PUBLISHED, _('Published')),
                                                  (ARCHIVED, _('Archived'))
                                              ), default=DRAFT)
    published_at = models.DateTimeField(
        _('Published At'),
        auto_now_add=False, auto_now=False, null=True, blank=True)

    likes = models.PositiveIntegerField(default=0)

    dislikes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

        indexes = [
            models.Index(fields=['author', 'status'], name='author_status_idx')
        ]
        ordering = ('-created_at',)


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    article = models.ForeignKey('articles.Article',
                                related_name='comments',
                                on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approved(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text
        # return '{} -> [{}]'.format(self.author.username, self.article)

articles/forms.py
from django import forms
from .models import Comment
from django.contrib.auth.models import User
from django.http import request


class CommentForm(forms.Form):

    comment_area = forms.CharField(
        label="",
        widget=forms.Textarea)

articles/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Comment
from django.views.generic import ListView, DetailView
from rubric.views import AllRubricMixin
from .forms import CommentForm
from django.shortcuts import redirect

from django.contrib import auth


class ListIndex(AllRubricMixin, ListView):
    model = Article
    template_name = 'articles/list.html'
    queryset = Article.objects.published()[:5]


class ArticleDetail(DetailView):
    template_name = 'articles/detail.html'
    # context_object_name = 'article_detail'  # or 'object' by default this name uses in forms
    model = Article

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleDetail, self).get_context_data(*args, **kwargs)
        context['article_detail'] = self.get_object()
        context['comments_by_article'] = self.get_object().comments.all()
        return context


def add_comment_to_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment()
            # comment = form.save(commit=False)
            comment.article = article
            comment.author = auth.get_user(request)
            comment.text = form.cleaned_data['comment_area']
            comment.save()
            return redirect('article-detail', pk=article.pk)
    else:
        form = CommentForm()
    return render(request, 'articles/add_comment_to_article.html', {'form': form})

articles/templates/articles/add_comment_to_article.html
{% extends "layout.html" %}

{%  block content %}
    <H1>New comment</H1>
    <form method="POST">
    	{% csrf_token %}
    	{{form.as_p}}
        <button type="submit" value="Add comment"> Send </button>
    </form>
{% endblock%}

articles/templates/articles/detail.html
{% extends "layout.html" %}

{%  block content %}
    <h1>{{ article_detail.rubric }}</h1>
    <h2>{{ article_detail.title }}</h2>
    <div>
    	{% if article_detail.image %}
            <p> <img src="{{article_detail.image.url}}" class="img-responsive"> </p>
        {% endif %}
    </div>
    <body>
	    {{ object.content }}
        <hr>

        <div>
            {% if user.is_authenticated %}
            <a href="{% url 'add_comment_to_article' pk=article.pk %}">Add comment</a>  
            <hr>
            {% else %}
            <p>Only authorized users can leave comments.</p>
            <hr>
            {% endif %}
        </div>

        {% for comment in  article.comments.all %}
            <div>
                <div>{{ comment.created_at }}</div>
                <strong>{{ comment.author }}</strong>
                <p>{{ comment.text|linebreaks }}</p>
            </div>
        {% empty %}
            <p>No comments here yet :(</p>
        {% endfor %}
    </body>
{% endblock%}

articles/templates/articles/list.html
{%  extends "layout.html" %} 
{# {% extends "rubric/rubric_list.html" %} #}

{% block left_menu %}
    <a href="{% url 'main' %}">Main page</a>
    <div>
        <p> Articles Rubric: </p>
        {% for rubric in rubrics %}
             <a href="/rubric/{{rubric.pk}}/">{{ rubric.rubric_name }}</a> |
        {% endfor %}
    </div>
{% endblock%}

{% block content %}
    {% if object_list %}
        <ul>
        {% for article in object_list %}
            <li><a href="/articles/{{article.pk}}/">{{article.title}}
            </a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no published articles yet. Wait quite a bit)</p>
    {% endif %}
{%  endblock %}